Added zip type
kirananto/friendly-mimes pull request #4
Opened 2021-08-18 04:15 UTC by kilakewe

Added zip folder type to types list

2021-08-18 19:43 UTC, kirananto requested changes

2021-08-18 19:43 UTC, kirananto commented on src/data.ts
>      "fileType": ".google-apps.video"
Are you sure the filetype of zip is of `.google-apps.video` ?

2021-08-18 19:45 UTC, kilakewe commented
The bottom most is, I also corrected a typo in the Google apps video file type

Regards,

Gage Keenan

On 19/08/2021, at 7:43 AM, Kiran Anto ***@***.***> wrote:

﻿
@kirananto requested changes on this pull request.

In src/data.ts:

> @@ -3516,7 +3516,12 @@ export const data = [
   },
   {
     "mime": "application/vnd.google-apps.video",
-    "name": "Google VIdeo",
+    "name": "Google Video",
+    "fileType": ".google-apps.video"
+  },
+    {
+    "mime": "application/x-zip-compressed",
+    "name": "Compressed Archive (zip)",
     "fileType": ".google-apps.video"
Are you sure the filetype of zip is of .google-apps.video ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-08-25 06:25 UTC, kilakewe reviewed
Added correct file type definition for Zip files.

2022-05-07 15:01 UTC, kirananto approved these changes

2022-05-07 15:01 UTC, merged